#spring:
#  main:
#    web-application-type: none
#  datasource:
#    url: "jdbc:h2:file:./data/test"
#    username: sa
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#  jpa:
#    generate-ddl: true
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
#    database: h2
#  datasource:
#    url: "jdbc:h2:mem:~/data/spells"
#    username: sa
#    driver-class-name: org.h2.Driver
#    password: pine

dnd:
  title: "D&D Spell Book"
  h2:
    debug: true
    in-memory: true
    file-path: "/data/spells"